name: Trigger Agent Toolkit Update

on:
  pull_request:
    types: [closed]

jobs:
  trigger-videodb-helper-update:
    if: ${{ github.event.pull_request.merged && github.event.pull_request.base.ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Agent Toolkit Update workflow via repository_dispatch
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ secrets.AGENT_TOOLKIT_TOKEN }}" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/video-db/agent-toolkit/dispatches \
               -d '{"event_type": "sdk-context-update", "client_payload": {"pr_number": ${{ github.event.pull_request.number }}}}'
               
